server:
  port: 8761 # eureka默认端口

spring:
  application:
    name:  eureka-server # 集群中的应用名称都是这个，不能分别写eureka-server-a,eureka-server-b,eureka-server-c

eureka:
  client:
    register-with-eureka: true # 向ureka注册中心注册自己
    fetch-registry: false # false表示自己是一个注册中心
    service-url:
      defaultZone: http://peer2:8762/eureka/,http://peer3:8763/eureka/ # 将自己注册到集群的其他eureka节点
  instance:
    hostname: peer1
    instance-id: ${eureka.instance.hostname}:${spring.application.name}:${server.port} # 主机名称 : 应用名称 : 端口
    prefer-ip-address: true # 以ip形式显示具体的服务信息
    lease-renewal-interval-in-seconds: 5 # 5秒。服务实例的续约时间间隔
