server:
  port: 8762

spring:
  application:
    name:  eureka-server

eureka:
  client:
    register-with-eureka: true
    fetch-registry: false # false表示自己是一个注册中心
    service-url:
      defaultZone: http://peer1:8761/eureka/,http://peer3:8763/eureka/
  instance:
    hostname: peer2
    instance-id: ${eureka.instance.hostname}:${spring.application.name}:${server.port}
    prefer-ip-address: true
    lease-renewal-interval-in-seconds: 5

