spring:
  redis:
    host: 192.168.64.129
    port: 6379
    database: 0
    timeout: 1800000 # 连接超时时间，毫秒
    lettuce:
      pool:
        max-active: 20 # 连接池最大连接数
        max-wait: -1   # 连接池阻塞等待时间
        max-idle: 5    # 连接池最大空闲连接
        min-idle: 0    # 连接池最小空闲连接
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource # 数据源
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/db01?useUnicode=true&characterEncoding=utf-8
    username: root
    password: 123456

server:
  port: 9090